### ISSUE TITLE
More detailed installations

### ISSUE THREAD

**Issue by domcross** [MycroftAI/mycroft-gui#11]
I had to install the following packages:

- git
- cmake
- g++
- extra-cmake-modules
- qtdeclarative5-dev
- libqt5websockets5-dev
- libqt5webview5-dev
- libkf5i18n-dev
- gettext
- libkf5plasma-dev
- libkf5kio-dev

`sudo apt install git cmake g++ extra-cmake-modules qtdeclarative5-dev libqt5websockets5-dev libqt5webview5-dev libkf5i18n-dev gettext libkf5plasma-dev libkf5kio-dev`

**Comment by dschmidt** [comment]
See https://github.com/MycroftAI/mycroft-gui/pull/9

**Comment by penrods** [comment]
I think #9 addresses this.  I'm closing it out.
