### ISSUE TITLE
dev_setup.sh: errors with invalid package kio-dev

### ISSUE THREAD

**Issue by MikClucas** [MycroftAI/mycroft-gui#47]
the dev-setup script errors when trying to install missing packages with:

`Package kio-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libkf5kio-dev`

manually installing the packages and the suggested replacement works fine and the gui starts up without problems. 
kio-dev appears more than once in the install list.

**Comment by NeonDaniel** [comment]
I did the same for Ubuntu 20.04

**Comment by HrGaertner** [comment]
I have also problems with qml or qt not sure yet... I use kubuntu 20.04

**Comment by forslund** [comment]
I think we need to add a check for Focal or newer where kio-dev has been replaced with libkf5kio-dev.

**Comment by KaspAdam** [comment]
Try entering `sudo nano dev_setup.sh` and deleting kio-dev from all `sudo apt install`

**Comment by AIIX** [comment]
This has been fixed with the latest commit, Added official support for K / Ubuntu 20.04 focal and variants to the setup script.
