### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by DeastinY** [MycroftAI/mycroft-gui#79]
Had to also run 
`sudo apt install qml-module-org-kde-kirigami`
on Ubuntu

**Comment by builderjer** [comment]
My Picroft has the same issue, but is not in the repositories.

Also the package
    libq5webview5-dev

**Comment by NeonDaniel** [comment]
also `qml-module-qtmultimedia` on Ubuntu

**Comment by krisgesling** [comment]
Hey I just submitted #105 to add `qml-module-qtmultimedia` and we previously added `libqt5webview5-dev`.

I haven't needed `qml-module-org-kde-kirigami` so I'm leaving that out for now unless we confirm that it really is necessary for something.

**Comment by krisgesling** [comment]
Talking to @AIIX last night and `qml-module-org-kde-kirigami` is not a direct dependency but should have been installed as part of the dependency tree. The other packages have been added and this seems to be working as expected on the latest Ubuntu so I'm going to close this issue for now.

If anyone still has trouble please re-open or create a new ticket as appropriate.
